# Generated by Django 3.2.4 on 2023-09-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230918_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pw',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
